repos:
# ----------------- Black -----------------
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black

# ----------------- Isort -----------------
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

# ----------------- MyPy -----------------
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy
      name: mypy
      additional_dependencies: ["pydantic[mypy]"]
# ----------------- Pylint -----------------
- repo: local
  hooks:
    - id: pylint
      name: pylint
      # entry: pylint  <-- On change Ã§a
      entry: bash -c "export PYTHONPATH=backend/src && pylint backend/src"
      language: python
      types: [python]
      # Ajout de l'argument pour utiliser ton fichier de config racine
      args: ["--rcfile=.pylintrc"]
